name: ASP.NET Application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
         6.0.x
         8.0.x

    - name: Restore dependencies
      run: dotnet restore ./GoShare.sln 

    - name: Build
      run: dotnet build ./GoShare.sln --configuration Release --no-restore

    - name: Mobile App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
       files: ./Api_Mobile/appsettings.json
      env:
       ConnectionStrings.GoShareAzure: ${{ secrets.ConnectionStrings }}
       Google: ${{ secrets.Google }}
       Twilio: ${{ secrets.Twilio }}
       Jwt: ${{ secrets.Jwt }}
       SpeedSMSAPI: ${{ secrets.SpeedSMSAPI }}

    - name: Admin App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
       files: ./Api_Admin/appsettings.json
      env:
       ConnectionStrings.GoShareAzure: ${{ secrets.ConnectionStrings }}
       Jwt: ${{ secrets.Jwt }}
       Admin: ${{ secrets.Admin }}

    - name: Publish Admin Api Project
      run: dotnet publish ./Api_Admin/Api_Admin.csproj --configuration Release --no-build --output ./publish/Admin_Api

    - name: Publish Mobile Api Project
      run: dotnet publish ./Api_Mobile/Api_Mobile.csproj --configuration Release --no-build --output ./publish/Mobile_Api

    - name: Deploy Mobile Api to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ApiMobile20231019122723/mobile
        publish-profile: ${{ secrets.ApiMobile20231019122723 }}
        package: './publish/Mobile_Api'

    - name: Deploy Admin Api to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ApiMobile20231019122723/admin
        publish-profile: ${{ secrets.ApiMobile20231019122723 }}
        package: './publish/Admin_Api'
